### ISSUE TITLE
Can only assign numerals in the JSON

### ISSUE THREAD

**Issue by churchymayer** [PyrexPi/prophet#4]
Maybe I'm missing something but as of right now I'm only able to name the Oracles with numeral values in the JSON. My team uses L1-3, R1-3 and Mid as callouts. Would be awesome if I could use letters too. Awesome job otherwise tho

**Comment by PyrexPi** [comment]
You can use letters already, just be sure to put the letters around double quotes like the following:
`{
  "A":  "A",
  "B":  "B",
  "F":  "F",
  "G":  "G",
  "D":  "D",
  "E":  "E",
  "C":  "C"
}`.

Report back if you have more problems related to this, but I've tested it and even responded on a reddit comment who had this issue and worked well. Thanks!

**Comment by darkelement1987** [comment]
@churchymayer you could use jsonlint.com to find syntax errors

**Comment by churchymayer** [comment]
That solved it, thanks a lot
