### ISSUE TITLE
Muting discord audio when openning prophet.exe

### ISSUE THREAD

**Issue by JeeerryZ** [PyrexPi/prophet#6]
When i open prophet.exe and it asks me which encounter listen, it's disable my discord audio, so i need to reconnect again

**Comment by PyrexPi** [comment]
Which device are you selecting? Is it the device you use on Discord? If so you can try unchecking exclusive mode on advanced settings on the device properties from the sound control panel.
This is the first time I hear about this so I'll need more details about how it happens.

**Comment by JeeerryZ** [comment]
i'm using my headset for discord and VB Audio Cable for prophet, disabling exclusive mode works perfectly, thx

**Comment by PyrexPi** [comment]
No problem! I'm closing the issue as completed. Thanks!
